SELECT
    ORDER_ID,
    COALESCE(
    TRY_TO_DATE(ORDER_DATE, 'MM/DD/YYYY'),
    TRY_TO_DATE(ORDER_DATE, 'DD-MM-YYYY')
    ) AS ORDER_DATE,
    COALESCE(
    TRY_TO_DATE(SHIP_DATE, 'MM/DD/YYYY'),
    TRY_TO_DATE(SHIP_DATE, 'DD-MM-YYYY')
    ) AS SHIP_DATE,
    YEAR(COALESCE(
    TRY_TO_DATE(ORDER_DATE, 'MM/DD/YYYY'),
    TRY_TO_DATE(ORDER_DATE, 'DD-MM-YYYY')
    )) AS ORDER_YEAR,
    CUSTOMER_NAME,
    SEGMENT,
    REGION,
    CATEGORY,
    SUB_CATEGORY,
    PRODUCT_NAME,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT,
    
    -- Calculated Metrics
    PROFIT / NULLIF(SALES, 0) * 100 AS PROFIT_MARGIN_PCT,
    SALES - PROFIT AS COST_PRICE,
    SALES / NULLIF(QUANTITY, 0) AS REVENUE_PER_UNIT

FROM {{ ref('stg_orders') }}
